version: "3.8"

services:
  app:
    build: .
    container_name: "go_app"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres_db
      DB_PASSWORD: postgres_db
      DB_NAME: postgres_db
    command: ./main
  postgres:
    image: postgres:latest
    container_name: "postgres_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_db
      POSTGRES_PASSWORD: postgres_db
      POSTGRES_DB: postgres_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
